config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :restaurants

  root 'restaurants#index'

  resources :restaurants
  resources :reviews

  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: { scope: [:city, :state, :zip] }
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: { is: 5, message: "is the wrong length (should be 5 characters)"}, format: { with: /[0-9][0-9]*/, message: "is not a number" }

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :body, presence: true
  validates :rating, presence: true, numericality: { only_iteger: true }, format: { with: /[1-5]/, message: "Must be between 1 - 5" }
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant: @restaurant)
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Restaurant added successfully.' }
      else
        format.html { render :new }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # GET /reviews/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id]) unless params[:restaurant_id].nil?
    @review = Review.new
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review added successfully.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.haml
= form_for(@restaurant) do |f|
  %div
    = f.label :name
    = f.text_field :name, placeholder: "Name"

  %div
    = f.label :address
    = f.text_field :address, placeholder: "Address"

  %div
    = f.label :city
    = f.text_field :city, placeholder: "City"

  %div
    = f.label :state
    = f.text_field :state, placeholder: "State"

  %div
    = f.label :zip
    = f.text_field :zip, placeholder: "Zip Code"

  %div
    = f.label :description
    = f.text_area :description, placeholder: "Description"

  - if @restaurant.errors.any?

    #error_explanation
      %h2
        = pluralize(@restaurant.errors.count, "error") + " prohibited this restaurant from being saved:"
      %ul
        =@restaurant.errors.full_messages.join(". ")
        - @restaurant.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit "Add Restaurant"

app/views/restaurants/index.html.haml
%p#notice= notice
%h1 Restaurants
%ul
  - @restaurants.each do |restaurant|
    %li= link_to restaurant.name, restaurant


%div= link_to 'Add New Restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
%h1 New Restaurant Form
%div= render 'form'
%div= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice


%h1= @restaurant.name
%hr/
%div= "Address: #{@restaurant.address}, #{@restaurant.city}, #{@restaurant.state} #{@restaurant.zip}"
%div= "Description: #{@restaurant.description}"

%div= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant)
%div= link_to 'Delete Restaurant', @restaurant, method: :delete, data: { confirm: 'Are you sure?' }

%hr
%h2 Reviews

%ul= render partial: "reviews/review", collection: @reviews

%hr

%div= link_to 'Add a Review', new_restaurant_review_path(@restaurant)
%div= link_to 'Back to Restaurants', restaurants_path

app/views/reviews/_form.html.haml
= form_for([@restaurant, @review]) do |f|
  %div
    = f.label :rating
    = f.text_field :rating, placeholder: "1-5"

  %div
    = f.label :body, "Review"
    = f.text_area :body

  - if @review.errors.any?
    #error_explanation
      %h2
        = pluralize(@review.errors.count, "error")
        prohibited this review from being saved:
      %ul
        = @review.errors.full_messages.join(". ")
        - @review.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit "Add Review"

app/views/reviews/_review.html.haml
-# loop
%li= "Rating: #{review.rating}"
%li= "Description: #{review.body}"
%li= "Created at: #{review.created_at.strftime("%B %d %Y")}"
%hr

app/views/reviews/new.html.haml
%h1= "Review Form for #{@restaurant.name}"
%div= render 'reviews/form'